Keep PIM secret and re-ask when user entered a wrong value
veracrypt/VeraCrypt pull request #1026
Opened 2023-01-13 20:52 UTC by bogdro

Since PIM is a part of the user's secret (the key is derived from it), as it is written:

> The PIM is treated like a secret value that must be entered by the user each time alongside the password.

(https://veracrypt.fr/en/Personal%20Iterations%20Multiplier%20(PIM).html?), it should also be hidden from view and not echoed to the terminal.

This patch addresses this issue.

Apart from this, PIM should be allowed to be re-entered, just like the password is, in case decryption fails. Otherwise, if the user enters the correct password and an incorrect PIM, he/she doesn't have a chance to fix the mistake - the process must be re-started.

This issue is also addressed.

2023-05-18 21:23 UTC, idrassi requested changes

2023-05-18 21:23 UTC, idrassi commented on src/Main/TextUserInterface.cpp
> +			if (!options.TrueCryptMode /*&& (options.Pim < 0) re-ask in case of wrong value entered*/)
Actually this is not the correct way to fix the issue. Instead, `options.Pim `should be set to -1 little bit below when we catch the exceptions `PasswordIncorrect `and `PasswordException` like what we do for `options.Password`.

2023-05-21 15:21 UTC, idrassi commented
I will merge this PR and do the changes that I mentionned on my comment directly.
Thank you.

2023-05-21 15:21 UTC, merged

2023-05-22 11:40 UTC, bogdro commented
Thank you.
Just like with https://github.com/veracrypt/VeraCrypt/pull/1025 - I didn't have the time to investigate this more. But, if the problem is fixed, whatever the way, I'm glad.

2023-05-22 19:48 UTC, idrassi commented
I have started experimenting with ChatGPT (GPT-4) and so I decided to see if it can find a fix for this issue. Since it cannot read the whole source code of VeraCrypt, I helped it by giving it the source code of the method TextUserInterface::MountVolume and telling it that the issue is in this method. After 2 seconds, it was able to implement the correct fix by setting the option.PIM to -1 in the correct places.

This is not very impressive since this is a simple case but it shows that maybe I should use ChatGPT (especially GPT-4) as a kind of reviewer to get a second option on specific changes.

Below are screenshots of the discussion:

![image](https://github.com/veracrypt/VeraCrypt/assets/4698669/96a1afd3-ae52-4259-904b-1e8fceb3d5a7)

![image](https://github.com/veracrypt/VeraCrypt/assets/4698669/75f228d7-d24f-4e6f-8c0f-497b9aae145b)

![image](https://github.com/veracrypt/VeraCrypt/assets/4698669/26273ad4-ab22-4a71-a8d4-6720ab89cd47)

![image](https://github.com/veracrypt/VeraCrypt/assets/4698669/bc9092fe-04a3-4ca4-8e03-40438d5b9fc6)

2023-05-23 08:43 UTC, bogdro commented
Interesting :)
I still prefer to write my own code, though, so that I know I'm the author :). And for the fun of learning.